config/routes.rb
Rails.application.routes.draw do
  root 'index#index'

  get 'express-delivery/index', to: 'express_delivery#index', as: 'express'

  post 'express-delivery/search', to: 'express_delivery#search', as: 'express_search'

  get 'cet/index', to: 'cet#index', as: 'cet'

  post 'cet/search', to: 'cet#search', as: 'cet_search'

  get 'avatar', to: 'avatar#index', as: 'avatar'
  
  post 'avatar/upload', to: 'avatar#upload', as: 'avatar_upload'

  resources :todo do
    member do
      get 'status'
    end
  end

  get 'weather', to: 'weather#index', as: 'weather'
  post 'weather/search', to: 'weather#search', as: 'weather_search'
end

app/models/todo.rb
# -*- encoding : utf-8 -*-
class Todo < ActiveRecord::Base
  validates :name, presence: { message: "TODO 名称不能为空"}

  def self.get_all_unfinish
    return self.where(status: false).order('id desc')
  end
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/avatar_controller.rb
# -*- encoding : utf-8 -*-
class AvatarController < ApplicationController
  def index
    @avatar_src_arr = []

    avatar_path = File.join(Rails.root, "public", "uploads", "avatar")

    # TODO better way to get files of a dir
    if File.directory?(avatar_path)
      Dir.entries(avatar_path).reject{|d| d == '.' || d == '..'}.each do |item|
        @avatar_src_arr.push(view_context.image_url("/uploads/avatar/#{item}"))
      end
    end
  end

  def upload
    uploader = AvatarUploader.new()
    avatar = params[:avatar]
    begin
      uploader.store!(avatar)
    rescue Exception => e
      render json: {"status" => "error", "message" => e.message} and return
    end

    render json: {"status" => "success", "url" => uploader.url}
  end
end

app/controllers/cet_controller.rb
# -*- encoding : utf-8 -*-
class CetController < ApplicationController
  def index
  end

  def search
    zkzh = params[:zkzh]
    xm = params[:xm]
    html = ApplicationHelper.get_cet_html(zkzh, xm)

    render plain: ApplicationHelper.get_cet_result(html)
  end
end

app/controllers/express_delivery_controller.rb
# -*- encoding : utf-8 -*-
require 'open-uri'

class ExpressDeliveryController < ApplicationController
  def index
  end

  def search
    url = "http://www.aikuaidi.cn/rest/?key=%s&order=%s&id=%s&ord=desc"
    key = Rails.application.config.order_key
    order_id = params[:order_id]
    com_code = ApplicationHelper.get_express_company order_id

    if not com_code
      render json: {"message" => "快递单号无效"} and return
    end
    content = open(url % [key, order_id, com_code]).read
    render json: content
  end
end

app/controllers/index_controller.rb
# -*- encoding : utf-8 -*-
class IndexController < ApplicationController
  def index
  end
end

app/controllers/todo_controller.rb
# -*- encoding : utf-8 -*-
class TodoController < ApplicationController

  def index
    @todos = Todo.get_all_unfinish
  end

  def create
    @todo = Todo.new(name: params[:name])
    
    if @todo.invalid?
      render json: {"status" => "error", "message" => @todo.errors} and return
    else
      @todo.save
      render json: {
        "status" => "success",
        "data" => {
          "id" => @todo.id,
          "name" => @todo.name,
          "status_url" => view_context.status_todo_url(:id => @todo.id),
        }
      } and return
    end

  end

  def status
    @todo = Todo.find_by_id(params[:id])

    if @todo
      @todo.update(status: !@todo.status)
      render json: {"status" => "success"} and return
    else
      render json: {"status" => "error", "message" => "无该记录"} and return
    end
  end

  def destroy
    @todo = Todo.find_by_id(params[:id])
    @todo.destroy if @todo

    render json: {"status" => "success"}
  end

end

app/controllers/weather_controller.rb
# -*- encoding : utf-8 -*-
class WeatherController < ApplicationController
  def index
  end

  def search
    cityCode = params[:cityCode]

    weather = ApplicationHelper.get_weather_html(cityCode)

    render plain: weather
  end

end

app/helpers/application_helper.rb
require 'open-uri'
require 'json'
require 'mechanize'
require 'logger'

module ApplicationHelper
  def self.get_express_company(order)
    url = "http://www.kuaidi100.com/autonumber/auto?num=" + order
    content = open(url).read
    if content.size <= 5
      return false
    else
      result = /comCode":"(.*?)"/.match(content)
      return result[1]
    end
  end

  def self.get_cet_html(zkzh, xm)
    url = "http://www.chsi.com.cn/cet/"
    agent = Mechanize.new do |a|
      a.log = Logger.new(STDOUT)
    end
    cet_page = agent.get url
    form = cet_page.forms[1]
    Rails.logger.debug(form)
    form.field_with(:name => "zkzh").value = zkzh
    form.field_with(:name => "xm").value = xm
    html = form.submit

    Rails.logger.debug(html.body)
    return html.body
  end 

  def self.get_cet_result(html)
    error = /error[\s|\S]*?>(.*?)<\/div>/.match(html)
    if error
      return error[1]
    else
      result = /m_cnt_m">([\s|\S]*?)<div class="psTxt/.match(html)
      Rails.logger.debug(result)
      return result[1]
    end
  end

  def self.get_weather_html(cityCode)
    url = "http://m.weather.com.cn/mweather/%s.shtml" % cityCode

    html = open(url).read
    weather = /"days7">([\s|\S]*?)<\/div>/.match(html)

    return weather[1]
  end
end

app/views/avatar/index.html.erb
<div class="fun">
    <a href="/"><button class="btn btn-1">FUN</button></a>
</div>
<div class="upload">
    <button class="btn btn-1" id="avatar-btn">UPLOAD</button>
    <input id="avatar" type="file" name="avatar" data-form-action="<%= avatar_upload_url %>">
</div>
<div class="panel">
    <div id="progress"></div>
    <div class="center" id="progress-num"><span><span></div>
     <div class="photo">
         <% @avatar_src_arr.each do |avatar|%>
         <div class="block">
             <img src="<%= avatar %>">
         </div>
         <% end%>
    </div>
</div>

app/views/cet/index.html.erb
<div class="fun">
    <a href="/"><button class="btn btn-1">FUN</button></a>
</div>
<div class="panel">
    <div>
        <form id="cet" action="<%= cet_search_url %>" method="post">
            <input id="zkzh" class="input middle col-10" type="text" name="zkzh" placeholder="准考证号, 15位" data-length="15" required />
            <input id="xm" class="input middle col-10" type="text" name="zkzh" placeholder="姓名" required />
            <button type="submit" class="btn btn-1" id="search">查找</button>
        </form>
        <div id="cet_container">
            <div class="loading">
                <img src="<%= image_url "loading.gif" %>">
            </div>
            <div id="cet_table">
            </div>
        </div>
    </div>
</div>

app/views/express_delivery/index.html.erb
<div class="fun">
    <a href="/"><button class="btn btn-1">FUN</button></a>
</div>
<div class="panel">
    <div>
        <form id="express" class="single-search" action="<%= express_search_url %>" method="post">
            <input id="order_id" class="input middle col-10" type="text" name="order_id" placeholder="快递订单号" required />
            <button type="submit" class="btn btn-1" id="search">查找</button>
        </form>
        <div id="order_container">
            <p class="msg" data-empty="暂无快递单号记录!"></p>
            <div class="loading">
                <img src="<%= image_url "loading.gif" %>">
            </div>
            <table id="order_list">
                <div>
                    <p><span>快递公司：</span><span id="com" class="red"></span>&nbsp;&nbsp;&nbsp;<span>物流状态:</span><span id="status" class="red"></span></p>
                </div>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/index/index.html.erb
<div class="center">
    <div class="head">
        <h2>实用工具</h2>
    </div>
    <ul class="lst">
        <li><a href="<%= express_url %>">快递单号查询</a></li>
        <li><a href="<%= cet_url %>">四六级查询</a></li>
        <li><a href="<%= avatar_url %>">实时上传头像</a></li>
        <li><a href="<%= todo_index_url %>">TODO LIST</a></li>
        <li><a href="<%= weather_url %>">天气查询</a></li>
    </ul>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-cn">
<head>
  <title>Fun</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'city', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<%= yield %>
</div>

<%= yield :js %>
</body>
</html>

app/views/todo/index.html.erb
<div class="fun">
    <a href="/"><button class="btn btn-1">FUN</button></a>
</div>
<div class="panel">
    <div>
        <form id="todo-form" action="<%= todo_index_url %>" method="post">
            <input id="todo-new" class="input middle col-10" type="text" name="name" placeholder="敲击回车添加任务" />
        </form>
        <div class="border-1 panel-c">
            <ul class="todo">
                <% @todos.each do |todo| %>
                    <li data-id="<%= todo.id %>" data-url-status="<%= status_todo_url :id => todo.id %>">
                        <div>
                            <span class="checkbox"><div class="checker"></div></span>
                            <div class="todo_si"><%= todo.name %></div>
                            <div class="delete">X</div>
                        </div>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/weather/index.html.erb
<div class="fun">
    <a href="/"><button class="btn btn-1">FUN</button></a>
</div>
<div class="panel">
    <div>
        <form id="weather_form" class="single-search" action="<%= weather_search_url %>" method="post">
            <input id="weather_id" class="input middle col-10" type="text" name="weather_id" placeholder="请输入城市" required />
            <button type="submit" class="btn btn-1" id="search">查找</button>
        </form>
        <div id="order_container">
            <div class="loading">
                <img src="<%= image_url "loading.gif" %>">
            </div>
            <div id="weather_container">
            </div>
        </div>
    </div>
</div>